"""rename chunks unique constraint to match model

Revision ID: 8435639de18d
Revises: caf086c941e8
Create Date: 2026-09-26 14:52:29.047190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8435639de18d'
down_revision: Union[str, Sequence[str], None] = 'caf086c941e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('chunks_file_id_chunk_index_key'), 'chunks', type_='unique')
    op.create_unique_constraint('uq_chunk_file_index', 'chunks', ['file_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chunk_file_index', 'chunks', type_='unique')
    op.create_unique_constraint(op.f('chunks_file_id_chunk_index_key'), 'chunks', ['file_id', 'chunk_index'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
